name: CD

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v4.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: https://api.opentrackmania.com
        PROJECT: opentrackmania-api
